/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'phungmanhcuong' at '7/12/16 9:26 AM' with Gradle 2.14
 *
 * @author phungmanhcuong, @date 7/12/16 9:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
